baseurl = "https://www.organicseodesign.co/"
languageCode = "en-us"
title = "Organic SEO Design"
theme = "hugo-theme-casper"
disqusShortname = ""
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10
canonifyurls = true
[menu]
   
    [[menu.main]]
    identifier = "/about/_index.md"
    name       = "about"
    url        = "/about"
    weight     = 2

    [[menu.main]]
    identifier = "/contact/_index.md"
    name       = "contact"
    url        = "/contact.html"
    weight     = 4
    
     [[menu.main]]
    identifier = "/organic-seo-company/_index.md"
    name       = "blog"
    url        = "/organic-seo-company/"
    weight     = 5
[params]
  description = "A bridge to organic SEO by design."
  cover = "images/cover.jpg"
  author = "Nathan M. Allen"
  authorlocation = "Orange County,CA,USA"
  authorwebsite = ""
  bio= "my bio"
  logo = "images/logo.png"
  googleAnalyticsUserID = ""

  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = "http://feeds.feedburner.com/..."
  githubName = "Nathan2014"
  twitterName = "organicseoco"
  # facebookName = ""
  # linkedinName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = true
  [params.social]
    twitter = "your_twitter"
    
    [outputs]
  home = ["HTML", "AMP"]
  page = ["HTML", "AMP"]
  blog = ["HTML", "AMP"]
